services:
  api:
    container_name: ase-server
    image: jbr/ase-server:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./.env:/opt/server/.env
      - ./data:/opt/server/data
    logging:
      # journalctl -f -t api
      driver: journald
      options:
        tag: api
    restart: unless-stopped
    networks:
      - default

  worker:
    container_name: ase-worker
    image: jbr/ase-worker:latest
    build:
      context: ./worker
      dockerfile: Dockerfile
    volumes:
      - ./.env:/opt/worker/.env
    logging:
      # journalctl -f -t worker
      driver: journald
      options:
        tag: worker
    restart: unless-stopped
    depends_on:
      api:
        condition: service_healthy
    networks:
      - default

networks:
  default:
    name: ase-network
    driver: bridge
