[tool.poetry]
name = "ase2025-worker"
version = "0.1.0"
description = "Worker part of the evaluation platform for Co4 competition."
authors = ["Ozren Dabić <ozren.dabic@jetbrains.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.32.3"
dotenv = "^0.9.9"
pyyaml = "^6.0.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
