### Healtcheck
GET http://localhost:{{port}}/

### Submit Evaluation
POST http://localhost:{{port}}/evaluate/
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="submission_file"; filename="input.jsonl"
Content-Type: application/json

< input.jsonl
--boundary
Content-Disposition: form-data; name="stage"

public
--boundary
Content-Disposition: form-data; name="language"

python
--boundary--
